# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.22.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.22.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/stanwu/Desktop/EE451_final_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/stanwu/Desktop/EE451_final_project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.22.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.22.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/stanwu/Desktop/EE451_final_project/CMakeFiles /Users/stanwu/Desktop/EE451_final_project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/stanwu/Desktop/EE451_final_project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GeneticAlgorithm

# Build rule for target.
GeneticAlgorithm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GeneticAlgorithm
.PHONY : GeneticAlgorithm

# fast build rule for target.
GeneticAlgorithm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeneticAlgorithm.dir/build.make CMakeFiles/GeneticAlgorithm.dir/build
.PHONY : GeneticAlgorithm/fast

algorithm/Chromosome.o: algorithm/Chromosome.cpp.o
.PHONY : algorithm/Chromosome.o

# target to build an object file
algorithm/Chromosome.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeneticAlgorithm.dir/build.make CMakeFiles/GeneticAlgorithm.dir/algorithm/Chromosome.cpp.o
.PHONY : algorithm/Chromosome.cpp.o

algorithm/Chromosome.i: algorithm/Chromosome.cpp.i
.PHONY : algorithm/Chromosome.i

# target to preprocess a source file
algorithm/Chromosome.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeneticAlgorithm.dir/build.make CMakeFiles/GeneticAlgorithm.dir/algorithm/Chromosome.cpp.i
.PHONY : algorithm/Chromosome.cpp.i

algorithm/Chromosome.s: algorithm/Chromosome.cpp.s
.PHONY : algorithm/Chromosome.s

# target to generate assembly for a file
algorithm/Chromosome.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeneticAlgorithm.dir/build.make CMakeFiles/GeneticAlgorithm.dir/algorithm/Chromosome.cpp.s
.PHONY : algorithm/Chromosome.cpp.s

algorithm/GeneticAlgorithm.o: algorithm/GeneticAlgorithm.cpp.o
.PHONY : algorithm/GeneticAlgorithm.o

# target to build an object file
algorithm/GeneticAlgorithm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeneticAlgorithm.dir/build.make CMakeFiles/GeneticAlgorithm.dir/algorithm/GeneticAlgorithm.cpp.o
.PHONY : algorithm/GeneticAlgorithm.cpp.o

algorithm/GeneticAlgorithm.i: algorithm/GeneticAlgorithm.cpp.i
.PHONY : algorithm/GeneticAlgorithm.i

# target to preprocess a source file
algorithm/GeneticAlgorithm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeneticAlgorithm.dir/build.make CMakeFiles/GeneticAlgorithm.dir/algorithm/GeneticAlgorithm.cpp.i
.PHONY : algorithm/GeneticAlgorithm.cpp.i

algorithm/GeneticAlgorithm.s: algorithm/GeneticAlgorithm.cpp.s
.PHONY : algorithm/GeneticAlgorithm.s

# target to generate assembly for a file
algorithm/GeneticAlgorithm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeneticAlgorithm.dir/build.make CMakeFiles/GeneticAlgorithm.dir/algorithm/GeneticAlgorithm.cpp.s
.PHONY : algorithm/GeneticAlgorithm.cpp.s

algorithm/Population.o: algorithm/Population.cpp.o
.PHONY : algorithm/Population.o

# target to build an object file
algorithm/Population.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeneticAlgorithm.dir/build.make CMakeFiles/GeneticAlgorithm.dir/algorithm/Population.cpp.o
.PHONY : algorithm/Population.cpp.o

algorithm/Population.i: algorithm/Population.cpp.i
.PHONY : algorithm/Population.i

# target to preprocess a source file
algorithm/Population.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeneticAlgorithm.dir/build.make CMakeFiles/GeneticAlgorithm.dir/algorithm/Population.cpp.i
.PHONY : algorithm/Population.cpp.i

algorithm/Population.s: algorithm/Population.cpp.s
.PHONY : algorithm/Population.s

# target to generate assembly for a file
algorithm/Population.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeneticAlgorithm.dir/build.make CMakeFiles/GeneticAlgorithm.dir/algorithm/Population.cpp.s
.PHONY : algorithm/Population.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeneticAlgorithm.dir/build.make CMakeFiles/GeneticAlgorithm.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeneticAlgorithm.dir/build.make CMakeFiles/GeneticAlgorithm.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GeneticAlgorithm.dir/build.make CMakeFiles/GeneticAlgorithm.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GeneticAlgorithm"
	@echo "... algorithm/Chromosome.o"
	@echo "... algorithm/Chromosome.i"
	@echo "... algorithm/Chromosome.s"
	@echo "... algorithm/GeneticAlgorithm.o"
	@echo "... algorithm/GeneticAlgorithm.i"
	@echo "... algorithm/GeneticAlgorithm.s"
	@echo "... algorithm/Population.o"
	@echo "... algorithm/Population.i"
	@echo "... algorithm/Population.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

